name: 'Choreo Configurable Check'
description: 'Support to check configurable lists for automated deployement in choreo'
author: WSO2
branding:
  icon: 'arrow-up-circle'
  color: 'orange'
inputs:
  configInput:
    description: 'List of existing configs'
    required: false
  appName:
    description: 'Application Name'
    required: false
  appId:
    description: 'Application ID'
    required: false
  envId:
    description: 'Environment ID'
    required: false
  versionId:
    description: 'API Version ID'
    required: false
  commitId:
    description: 'Source Commit ID'
    required: false
  runId:
    description: 'Run ID'
    required: false
  alertProxyURL:
    description: 'Alerting API Proxy URL'
    required: false
  subPath:
    description: 'Working directory of script'
    required: false
  existingConfigSchema:
    description: 'Existing Config Schema'
    required: false
  cronFrequencyAvailability:
    description: 'Cron frequency availability'
    required: false
  configurableUpdateURL:
    description: 'Configurable Update API Proxy URL'
    required: false
outputs:
  choreo-status:
    description: 'Status of operation'
runs:
  using: 'node16'
  main: 'dist/index.js'
